name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Decrypt keypair.snk
      env:
        KEYPAIR_GPG_PASSPHRASE: ${{ secrets.KEYPAIR_GPG_PASSPHRASE }}
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$KEYPAIR_GPG_PASSPHRASE" --output keypair.snk keypair.snk.gpg
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
        dotnet build --no-restore --configuration Release
    - name: Test 
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: |
        cd Awaitable/bin/Release
        dotnet nuget push "*.nupkg" --api-key "$NUGET_KEY" --source https://api.nuget.org/v3/index.json
